from typing import Protocol, runtime_checkable
from shared.generics.pagination import PaginatedResult, PaginationParams
from ...domain import Product


@runtime_checkable
class IProductRepo(Protocol):
    def get_by_id(self, product_id: int) -> Product | None: ...

    def get_paginated(self, params: PaginationParams) -> PaginatedResult[Product]: ...

    def get_random(self, limit: int) -> list[Product]: ...

    def search(
        self, query: str, params: PaginationParams
    ) -> PaginatedResult[Product]: ...

    def create(self, product: Product) -> Product: ...

    def update(self, product: Product) -> Product: ...

    def delete(self, product_id: int) -> bool: ...

    def swap_ids(self, id_a: int, id_b: int) -> None: ...
