from datetime import datetime
from typing import Protocol, runtime_checkable
from ..domain import User


@runtime_checkable
class IAdminRepo(Protocol):
    def get_by_login(self, login: str) -> User | None: ...
    def get_by_id(self, user_id: int) -> User | None: ...
    def update_password(
        self,
        user_id: int,
        password_hash: str,
        password_changed_at: datetime | None = None,
    ) -> User | None: ...
    def update_telegram_chat_id(self, user_id: int, chat_id: str | None) -> User | None: ...
    def list_order_notification_recipients(self) -> list[User]: ...
    def set_recovery_code(self, user_id: int, code_hash: str, expires: datetime) -> None: ...
    def record_recovery_failure(self, user_id: int, attempts: int, locked_until: datetime | None) -> None: ...
    def clear_recovery_code(self, user_id: int) -> None: ...
