from datetime import datetime
from typing import Protocol

from access.domain import Customer


class ICustomerRepo(Protocol):
    def get_by_email(self, email: str) -> Customer | None: ...
    def get_by_id(self, customer_id: int) -> Customer | None: ...
    def create(self, *, email: str, password_hash: str) -> Customer: ...
    def update_password(self, customer_id: int, password_hash: str) -> None: ...
    def set_recovery_code(
        self, customer_id: int, code_hash: str, expires: datetime
    ) -> None: ...
    def clear_recovery_code(self, customer_id: int) -> None: ...
    def record_recovery_failure(
        self,
        customer_id: int,
        attempts: int,
        locked_until: datetime | None,
    ) -> None: ...
    def get_token_version(self, customer_id: int) -> int | None: ...
    def bump_token_version(self, customer_id: int) -> int: ...
    def update_last_login(self, customer_id: int, when: datetime) -> None: ...
