from typing import Protocol

from ...domain.snapshot_vo import SnapshotInfo


class ISnapshotStorage(Protocol):
    def list(self) -> list[SnapshotInfo]: ...
    def info(self, name: str) -> SnapshotInfo | None: ...
    def path_of(self, name: str) -> str: ...
    def delete(self, name: str) -> None: ...
    def rotate(self, keep: int) -> int: ...
    def available_bytes(self) -> int: ...
